server:
  port: 8080
#
#logging:
#  level:
#    root: INFO
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
#    org.springframework.web: DEBUG

spring:
  profiles:
    include: secret
  servlet:
    multipart:
      max-file-size: 100MB         # ê°œë³„ íŒŒì¼ ë‹¹ ìµœëŒ€ ìš©ëŸ‰
      max-request-size: 100MB      # HTTP ìš”ì²­ ë‹¹ ìµœëŒ€ ì „ì²´ ìš©ëŸ‰

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000

  jpa:
    open-in-view: false  # ğŸ‘ˆ ì´ ì¤„ì„ ì¶”ê°€í•´ ì£¼ì„¸ìš”!
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

neis:
  api:
    key: ${NEIS_API_KEY:5c2f9ee4dec94ff4a53bf00bb3c3df4e}
    atpt-code: ${NEIS_ATPT_CODE:C10}
    schul-code: ${NEIS_SCHOOL_CODE:7150658}