spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 293668175344-20uv67g5u9dvsmnu0ftv95d4b5tlnfja.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  mail:
    username: startea0716@gmail.com
    password: uhfp gbsx lyls lrbo

  datasource:
    url: jdbc:mysql://localhost:3306/bssm_meal?useSSL=false&allowPublicKeyRetrieval=true
    username: backendsrv
    password: dlawpals10
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        # MariaDB에서 불필요한 메타데이터 조회를 막아 에러를 방지합니다.
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.MySQLDialect
jwt:
  client-id: 293668175344-20uv67g5u9dvsmnu0ftv95d4b5tlnfja.apps.googleusercontent.com  # JwtService용
  secret: ${JWT_SECRET:a4f6b28c91d3e572f8a0c4b6e8d192a3}
  access-expire-millis: 43200000
  refresh-expire-millis: 1209600000
