server:
  port: 8080
  forward-headers-strategy: native
  tomcat:
    # 대용량 파일 전송 시 연결이 끊기지 않도록 타임아웃을 넉넉히 설정 (30초)
    connection-timeout: 30000
#
#logging:
#  level:
#    root: INFO
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
#    org.springframework.web: DEBUG

spring:
  profiles:
    include: secret
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB         # 개별 파일 당 최대 용량
      max-request-size: 100MB      # HTTP 요청 당 최대 전체 용량
      file-size-threshold: 0

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    profiles:
      include: secret
    redis:
      host: localhost
      port: 6379

neis:
  api:
    key: ${NEIS_API_KEY:5c2f9ee4dec94ff4a53bf00bb3c3df4e}
    atpt-code: ${NEIS_ATPT_CODE:C10}
    schul-code: ${NEIS_SCHOOL_CODE:7150658}